// Minimal Template-Auslagerung ohne Funktionalitätsänderung
function loginTemplate(errorFlag) {
  return `<!DOCTYPE html><html lang="de"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>Admin Login - Hausarztpraxis Airoud</title><link rel="stylesheet" href="/styles.css"><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"><style>.login-container{min-height:100vh;display:flex;align-items:center;justify-content:center;background:linear-gradient(135deg,var(--primary-color),var(--secondary-color))}.login-form{background:#fff;padding:3rem;border-radius:var(--border-radius);box-shadow:var(--shadow-heavy);width:100%;max-width:400px}.login-form h2{text-align:center;margin-bottom:2rem;color:var(--text-dark)}.form-group{margin-bottom:1.5rem}.form-group label{display:block;margin-bottom:.5rem;color:var(--text-dark);font-weight:500}.form-group input{width:100%;padding:.75rem;border:2px solid var(--gray-light);border-radius:var(--border-radius);font-size:1rem;transition:var(--transition)}.form-group input:focus{outline:none;border-color:var(--primary-color)}.login-btn{width:100%;padding:.75rem;background:var(--primary-color);color:#fff;border:none;border-radius:var(--border-radius);font-size:1rem;font-weight:600;cursor:pointer;transition:var(--transition)}.login-btn:hover{background:var(--secondary-color)}.error{color:var(--danger);text-align:center;margin-top:1rem}.praxis-logo{text-align:center;margin-bottom:2rem}.praxis-logo i{font-size:3rem;color:var(--primary-color);margin-bottom:.5rem}</style></head><body><div class="login-container"><div class="login-form"><div class="praxis-logo"><i class="fas fa-user-md"></i><h3>Hausarztpraxis Airoud</h3></div><h2>Admin Login</h2><form method="POST" action="/admin/login"><div class="form-group"><label for="username">Benutzername:</label><input type="text" id="username" name="username" required></div><div class="form-group"><label for="password">Passwort:</label><input type="password" id="password" name="password" required></div><button type="submit" class="login-btn">Anmelden</button>${errorFlag ? '<div class="error">Ungültige Anmeldedaten</div>' : ''}</form></div></div></body></html>`;
}

function adminLayout(innerHtml) {
  return `<!DOCTYPE html><html lang="de"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>CMS Admin - Hausarztpraxis Airoud</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap" rel="stylesheet"><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"><link rel="stylesheet" href="/cms-admin-styles.css"></head><body>${innerHtml}<script src="/cms-admin-enhanced.js"></script></body></html>`;
}

module.exports = { loginTemplate, adminLayout };
